"""Custom Tests Manager"""

from pathlib import Path
import os
from datetime import datetime
import numpy as np
import pandas as pd
import deeplabcut
import cv2
from ..utils.logger import setup_logger

logger = setup_logger(__name__)

class TestsManager:
    """Manager for custom user tests post-inference"""

    def __init__(self):
        pass

    def get_analyzed_data_file(self, config_path: str, video_path: str) -> str | None:
        """Find the .h5 file generated by DLC for a given video"""
        # Look for .h5 files that start with the video name
        video_name = Path(video_path).stem
        video_dir = Path(video_path).parent
        
        h5_files = list(video_dir.glob(f"{video_name}*.h5"))
        if h5_files:
            return str(sorted(h5_files, key=os.path.getmtime)[-1])
        return None

    def analyze_video_if_needed(self, config_path: str, video_path: str, shuffle: int = 1) -> str:
        """Run DLC analysis on the video if the .h5 file doesn't exist"""
        h5_file = self.get_analyzed_data_file(config_path, video_path)
        if h5_file and os.path.exists(h5_file):
            logger.info(f"Found existing analysis file: {h5_file}")
            return h5_file
            
        logger.info(f"Running DLC analysis on {video_path}...")
        deeplabcut.analyze_videos(
            config_path, 
            [video_path], 
            shuffle=shuffle, 
            save_as_csv=False, 
            destfolder=str(Path(video_path).parent)
        )
        
        h5_file = self.get_analyzed_data_file(config_path, video_path)
        if not h5_file:
            logger.error(f"Failed to generate analysis file for {video_path}")
            raise RuntimeError("Failed to generate analysis .h5 file. Check DLC logs.")
            
        logger.info(f"Analysis completed: {h5_file}")
        return h5_file

    def get_video_info(self, video_path: str) -> tuple[float, int, int]:
        """Get FPS, Width, Height of video"""
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            return 30.0, 640, 480
        fps = cap.get(cv2.CAP_PROP_FPS)
        w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        cap.release()
        return fps, w, h
        
    def calculate_box_sides_time(self, h5_file: str, line_x: int, fps: float) -> dict:
        """
        Calculate time spent in Side Left (A) vs Side Right (B) based on vertical line_x.
        State changes only when ALL valid body parts cross to the other side.
        """
        df = pd.read_hdf(h5_file)
        
        # DataFrame MultiIndex structure: (scorer, bodypart, coords)
        scorer = df.columns.levels[0][0]
        bodyparts = df.columns.levels[1]
        
        total_frames = len(df)
        
        current_side = None # 'Left' or 'Right'
        frames_left = 0
        frames_right = 0
        
        # Iterate over frames
        # We can optimize this using Pandas/Numpy if it's too slow in Python loops,
        # but for typical video lengths (30 mins at 30 fps = 54k frames), a loop is okay.
        
        # Extract X coordinates and likelihoods as numpy arrays for speed
        x_data = df.xs('x', level='coords', axis=1)[scorer].values  # shape: (frames, bodyparts)
        like_data = df.xs('likelihood', level='coords', axis=1)[scorer].values # shape: (frames, bodyparts)
        
        for i in range(total_frames):
            frame_x = x_data[i]
            frame_like = like_data[i]
            
            # Mask of valid parts
            valid_mask = (frame_like > 0.6) & (~np.isnan(frame_x))
            valid_x = frame_x[valid_mask]
            
            valid_count = len(valid_x)
            
            if valid_count > 0:
                parts_on_left = np.sum(valid_x < line_x)
                parts_on_right = np.sum(valid_x >= line_x)
                
                if current_side is None:
                    # Initially, majority rules
                    current_side = 'Left' if parts_on_left > parts_on_right else 'Right'
                
                # Change state only if ALL valid parts cross the line
                if current_side == 'Left' and parts_on_right == valid_count:
                    current_side = 'Right'
                elif current_side == 'Right' and parts_on_left == valid_count:
                    current_side = 'Left'
                    
            if current_side == 'Left':
                frames_left += 1
            elif current_side == 'Right':
                frames_right += 1
                
        time_left = frames_left / fps if fps > 0 else 0
        time_right = frames_right / fps if fps > 0 else 0
        
        # Save results to Excel
        test_dir = Path(h5_file).parent / "tests_results"
        test_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        excel_path = test_dir / f"test-{timestamp}.xlsx"
        
        results = {
            "frames_A": frames_left,
            "frames_B": frames_right,
            "time_A_sec": time_left,
            "time_B_sec": time_right,
            "total_frames": total_frames,
            "fps": fps,
            "saved_file": str(excel_path)
        }
        
        # Create a simple DataFrame for the Excel file
        df_results = pd.DataFrame([results])
        df_results.to_excel(excel_path, index=False)
        
        logger.info(f"Saved test results to {excel_path}")
        return results

